name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Install Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: late

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Generate image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/${{ github.repository }}

    - name: Push container images tag
      uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64
        push: true
        labels: ${{ steps.meta.outputs.labels }}
        file: Dockerfile
        tags: |
          ghcr.io/${{ github.repository }}:latest
